//
// FormGeneratorAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class FormGeneratorAPI {
    /**

     - parameter tableName: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func formGeneratorGetColumns(tableName: String? = nil, completion: @escaping ((_ data: [FormGeneratorResponse]?,_ error: Error?) -> Void)) {
        formGeneratorGetColumnsWithRequestBuilder(tableName: tableName).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/FormGenerator/GetColumns
     - 

     - examples: [{contentType=application/json, example=[ {
  "value" : {
    "key" : {
      "key" : "value"
    }
  },
  "key" : "key"
}, {
  "value" : {
    "key" : {
      "key" : "value"
    }
  },
  "key" : "key"
} ]}]
     - parameter tableName: (query)  (optional)

     - returns: RequestBuilder<[FormGeneratorResponse]> 
     */
    open class func formGeneratorGetColumnsWithRequestBuilder(tableName: String? = nil) -> RequestBuilder<[FormGeneratorResponse]> {
        let path = "/api/FormGenerator/GetColumns"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "tableName": tableName
        ])


        let requestBuilder: RequestBuilder<[FormGeneratorResponse]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
