//
// StoredProceduresAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class StoredProceduresAPI {
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func storedProceduresExecuteCustomerList(body: CustomerListRequest, completion: @escaping ((_ data: ResponseOfCustomerListResponse?,_ error: Error?) -> Void)) {
        storedProceduresExecuteCustomerListWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/StoredProcedures/ExecuteCustomerList
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : ""
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<ResponseOfCustomerListResponse> 
     */
    open class func storedProceduresExecuteCustomerListWithRequestBuilder(body: CustomerListRequest) -> RequestBuilder<ResponseOfCustomerListResponse> {
        let path = "/api/StoredProcedures/ExecuteCustomerList"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ResponseOfCustomerListResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
