//
// TableComboboxSettingsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class TableComboboxSettingsAPI {
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func tableComboboxSettingsDelete(body: TableComboboxSettings, completion: @escaping ((_ data: ResponseOfBoolean?,_ error: Error?) -> Void)) {
        tableComboboxSettingsDeleteWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TableComboboxSettings/Delete
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : true
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<ResponseOfBoolean> 
     */
    open class func tableComboboxSettingsDeleteWithRequestBuilder(body: TableComboboxSettings) -> RequestBuilder<ResponseOfBoolean> {
        let path = "/api/TableComboboxSettings/Delete"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ResponseOfBoolean>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter tableName: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func tableComboboxSettingsGetItem(tableName: String? = nil, completion: @escaping ((_ data: ResponseOfTableComboboxSettings?,_ error: Error?) -> Void)) {
        tableComboboxSettingsGetItemWithRequestBuilder(tableName: tableName).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TableComboboxSettings/GetItem
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : ""
}}]
     - parameter tableName: (query)  (optional)

     - returns: RequestBuilder<ResponseOfTableComboboxSettings> 
     */
    open class func tableComboboxSettingsGetItemWithRequestBuilder(tableName: String? = nil) -> RequestBuilder<ResponseOfTableComboboxSettings> {
        let path = "/api/TableComboboxSettings/GetItem"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "TableName": tableName
        ])


        let requestBuilder: RequestBuilder<ResponseOfTableComboboxSettings>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func tableComboboxSettingsInsert(body: TableComboboxSettings, completion: @escaping ((_ data: ResponseOfLong?,_ error: Error?) -> Void)) {
        tableComboboxSettingsInsertWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TableComboboxSettings/Insert
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : 6
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<ResponseOfLong> 
     */
    open class func tableComboboxSettingsInsertWithRequestBuilder(body: TableComboboxSettings) -> RequestBuilder<ResponseOfLong> {
        let path = "/api/TableComboboxSettings/Insert"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ResponseOfLong>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func tableComboboxSettingsList(body: ListRequest, completion: @escaping ((_ data: ResponseOfListOfTableComboboxSettings?,_ error: Error?) -> Void)) {
        tableComboboxSettingsListWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TableComboboxSettings/List
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : [ {
    "stringFormat" : "stringFormat",
    "refTableName" : "refTableName",
    "refTableColumnId" : "refTableColumnId",
    "refIdColumn" : "refIdColumn",
    "textColumns" : "textColumns",
    "tableName" : "tableName",
    "idColumn" : "idColumn"
  }, {
    "stringFormat" : "stringFormat",
    "refTableName" : "refTableName",
    "refTableColumnId" : "refTableColumnId",
    "refIdColumn" : "refIdColumn",
    "textColumns" : "textColumns",
    "tableName" : "tableName",
    "idColumn" : "idColumn"
  } ]
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<ResponseOfListOfTableComboboxSettings> 
     */
    open class func tableComboboxSettingsListWithRequestBuilder(body: ListRequest) -> RequestBuilder<ResponseOfListOfTableComboboxSettings> {
        let path = "/api/TableComboboxSettings/List"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ResponseOfListOfTableComboboxSettings>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func tableComboboxSettingsTotalItemCount(completion: @escaping ((_ data: ResponseOfInteger?,_ error: Error?) -> Void)) {
        tableComboboxSettingsTotalItemCountWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TableComboboxSettings/TotalItemCount
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : 6
}}]

     - returns: RequestBuilder<ResponseOfInteger> 
     */
    open class func tableComboboxSettingsTotalItemCountWithRequestBuilder() -> RequestBuilder<ResponseOfInteger> {
        let path = "/api/TableComboboxSettings/TotalItemCount"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ResponseOfInteger>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func tableComboboxSettingsUpdate(body: TableComboboxSettings, completion: @escaping ((_ data: ResponseOfBoolean?,_ error: Error?) -> Void)) {
        tableComboboxSettingsUpdateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TableComboboxSettings/Update
     - 

     - examples: [{contentType=application/json, example={
  "code" : 0,
  "message" : "message",
  "value" : true
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<ResponseOfBoolean> 
     */
    open class func tableComboboxSettingsUpdateWithRequestBuilder(body: TableComboboxSettings) -> RequestBuilder<ResponseOfBoolean> {
        let path = "/api/TableComboboxSettings/Update"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ResponseOfBoolean>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
