//
// Authorizations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Authorizations: Codable {

    public var _id: Int?
    public var name: String?
    public var itemType: String?

    public init(_id: Int? = nil, name: String? = nil, itemType: String? = nil) {
        self._id = _id
        self.name = name
        self.itemType = itemType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case itemType
    }

}
