//
// AuthorizationItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthorizationItem: Codable {

    public var authorizationId: Int?
    public var authorizationTypes: [AuthorizationTypeItem]?

    public init(authorizationId: Int? = nil, authorizationTypes: [AuthorizationTypeItem]? = nil) {
        self.authorizationId = authorizationId
        self.authorizationTypes = authorizationTypes
    }


}
