//
// CustomerListRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerListRequest: Codable {

    public var pageNumber: Int?
    public var pageSize: Int?
    public var customerNo: Int?

    public init(pageNumber: Int? = nil, pageSize: Int? = nil, customerNo: Int? = nil) {
        self.pageNumber = pageNumber
        self.pageSize = pageSize
        self.customerNo = customerNo
    }


}
