//
// CustomerList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerList: Codable {

    public var _id: Int?
    public var name: String?
    public var surname: String?
    public var isActive: Bool?
    public var amount: Decimal?
    public var phone: String?
    public var email: String?
    public var operationDate: Date?

    public init(_id: Int? = nil, name: String? = nil, surname: String? = nil, isActive: Bool? = nil, amount: Decimal? = nil, phone: String? = nil, email: String? = nil, operationDate: Date? = nil) {
        self._id = _id
        self.name = name
        self.surname = surname
        self.isActive = isActive
        self.amount = amount
        self.phone = phone
        self.email = email
        self.operationDate = operationDate
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case surname
        case isActive
        case amount
        case phone
        case email
        case operationDate
    }

}
