//
// CustomerListResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerListResponse: Codable {

    public var returnTable: [CustomerList]?

    public init(returnTable: [CustomerList]? = nil) {
        self.returnTable = returnTable
    }


}
