//
// FormGeneratorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FormGeneratorResponse: Codable {

    public var key: String?
    public var value: [String:[String:String]]?

    public init(key: String? = nil, value: [String:[String:String]]? = nil) {
        self.key = key
        self.value = value
    }


}
