//
// GcolumnTypes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GcolumnTypes: Codable {

    public var _id: Int?
    public var typeName: String?

    public init(_id: Int? = nil, typeName: String? = nil) {
        self._id = _id
        self.typeName = typeName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case typeName
    }

}
