//
// Gcolumns.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Gcolumns: Codable {

    public var _id: Int?
    public var tableId: Int?
    public var columnName: String?
    public var columnTypeId: Int?
    public var isIdentity: Bool?
    public var isPrimaryKey: Bool?
    public var isNullable: Bool?
    public var defaultValue: String?
    public var labelText: String?
    public var validationMessage: String?
    public var placeholderText: String?

    public init(_id: Int? = nil, tableId: Int? = nil, columnName: String? = nil, columnTypeId: Int? = nil, isIdentity: Bool? = nil, isPrimaryKey: Bool? = nil, isNullable: Bool? = nil, defaultValue: String? = nil, labelText: String? = nil, validationMessage: String? = nil, placeholderText: String? = nil) {
        self._id = _id
        self.tableId = tableId
        self.columnName = columnName
        self.columnTypeId = columnTypeId
        self.isIdentity = isIdentity
        self.isPrimaryKey = isPrimaryKey
        self.isNullable = isNullable
        self.defaultValue = defaultValue
        self.labelText = labelText
        self.validationMessage = validationMessage
        self.placeholderText = placeholderText
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case tableId
        case columnName
        case columnTypeId
        case isIdentity
        case isPrimaryKey
        case isNullable
        case defaultValue
        case labelText
        case validationMessage
        case placeholderText
    }

}
