//
// GroupAuthorizations.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GroupAuthorizations: Codable {

    public var groupId: Int?
    public var authorizations: [AuthorizationItem]?

    public init(groupId: Int? = nil, authorizations: [AuthorizationItem]? = nil) {
        self.groupId = groupId
        self.authorizations = authorizations
    }


}
