//
// ListRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ListRequest: Codable {

    public var pageNumber: Int?
    public var pageSize: Int?

    public init(pageNumber: Int? = nil, pageSize: Int? = nil) {
        self.pageNumber = pageNumber
        self.pageSize = pageSize
    }


}
