//
// PhotoGalery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PhotoGalery: Codable {

    public var _id: Int?
    public var text: String?
    public var image: Data?
    public var _description: String?

    public init(_id: Int? = nil, text: String? = nil, image: Data? = nil, _description: String? = nil) {
        self._id = _id
        self.text = text
        self.image = image
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case text
        case image
        case _description = "description"
    }

}
