//
// PortalLoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PortalLoginResponse: Codable {

    public var _id: Int?
    public var groupId: Int?
    public var name: String?
    public var surname: String?
    public var username: String?
    public var email: String?
    public var gsm: String?

    public init(_id: Int? = nil, groupId: Int? = nil, name: String? = nil, surname: String? = nil, username: String? = nil, email: String? = nil, gsm: String? = nil) {
        self._id = _id
        self.groupId = groupId
        self.name = name
        self.surname = surname
        self.username = username
        self.email = email
        self.gsm = gsm
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case groupId
        case name
        case surname
        case username
        case email
        case gsm
    }

}
