//
// ResponseOfListOfAuthorizationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseOfListOfAuthorizationType: Codable {

    public var message: String?
    public var code: Int?
    public var value: [AuthorizationType]?

    public init(message: String? = nil, code: Int? = nil, value: [AuthorizationType]? = nil) {
        self.message = message
        self.code = code
        self.value = value
    }


}
