//
// ResponseOfTableComboboxSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseOfTableComboboxSettings: Codable {

    public var message: String?
    public var code: Int?
    public var value: OneOfResponseOfTableComboboxSettingsValue?

    public init(message: String? = nil, code: Int? = nil, value: OneOfResponseOfTableComboboxSettingsValue? = nil) {
        self.message = message
        self.code = code
        self.value = value
    }


}
