//
// ResponseOfListOfUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseOfListOfUser: Codable {

    public var message: String?
    public var code: Int?
    public var value: [User]?

    public init(message: String? = nil, code: Int? = nil, value: [User]? = nil) {
        self.message = message
        self.code = code
        self.value = value
    }


}
