//
// ResponseOfLong.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseOfLong: Codable {

    public var message: String?
    public var code: Int?
    public var value: Int64?

    public init(message: String? = nil, code: Int? = nil, value: Int64? = nil) {
        self.message = message
        self.code = code
        self.value = value
    }


}
