//
// ResponseOfListOfPhotoGalery.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseOfListOfPhotoGalery: Codable {

    public var message: String?
    public var code: Int?
    public var value: [PhotoGalery]?

    public init(message: String? = nil, code: Int? = nil, value: [PhotoGalery]? = nil) {
        self.message = message
        self.code = code
        self.value = value
    }


}
