//
// SbBackupScripts.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SbBackupScripts: Codable {

    public var backupId: Int?
    public var backupName: String?
    public var schemaScript: Data?
    public var tableScript: Data?
    public var viewScript: Data?
    public var storedProcedureScript: Data?
    public var userDefinedFunctionScript: Data?
    public var configurationDataScript: Data?
    public var truncateTableScript: Data?
    public var backupDate: Date?
    public var backupUser: String?

    public init(backupId: Int? = nil, backupName: String? = nil, schemaScript: Data? = nil, tableScript: Data? = nil, viewScript: Data? = nil, storedProcedureScript: Data? = nil, userDefinedFunctionScript: Data? = nil, configurationDataScript: Data? = nil, truncateTableScript: Data? = nil, backupDate: Date? = nil, backupUser: String? = nil) {
        self.backupId = backupId
        self.backupName = backupName
        self.schemaScript = schemaScript
        self.tableScript = tableScript
        self.viewScript = viewScript
        self.storedProcedureScript = storedProcedureScript
        self.userDefinedFunctionScript = userDefinedFunctionScript
        self.configurationDataScript = configurationDataScript
        self.truncateTableScript = truncateTableScript
        self.backupDate = backupDate
        self.backupUser = backupUser
    }


}
