//
// TableComboboxSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TableComboboxSettings: Codable {

    public var tableName: String?
    public var idColumn: String?
    public var refTableName: String?
    public var refTableColumnId: String?
    public var refIdColumn: String?
    public var textColumns: String?
    public var stringFormat: String?

    public init(tableName: String? = nil, idColumn: String? = nil, refTableName: String? = nil, refTableColumnId: String? = nil, refIdColumn: String? = nil, textColumns: String? = nil, stringFormat: String? = nil) {
        self.tableName = tableName
        self.idColumn = idColumn
        self.refTableName = refTableName
        self.refTableColumnId = refTableColumnId
        self.refIdColumn = refIdColumn
        self.textColumns = textColumns
        self.stringFormat = stringFormat
    }


}
