//
// TestTable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TestTable: Codable {

    public var _id: Int?
    public var name: String?
    public var telefon: String?

    public init(_id: Int? = nil, name: String? = nil, telefon: String? = nil) {
        self._id = _id
        self.name = name
        self.telefon = telefon
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case telefon
    }

}
