//
// UpdateGroupAuthorizationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateGroupAuthorizationRequest: Codable {

    public var groupId: Int?
    public var authorizationId: Int?
    public var authorizationTypeId: Int?
    public var value: Int?

    public init(groupId: Int? = nil, authorizationId: Int? = nil, authorizationTypeId: Int? = nil, value: Int? = nil) {
        self.groupId = groupId
        self.authorizationId = authorizationId
        self.authorizationTypeId = authorizationTypeId
        self.value = value
    }


}
