//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: Int?
    public var groupId: Int?
    public var name: String?
    public var surname: String?
    public var username: String?
    public var email: String?
    public var gsm: String?
    public var password: String?
    public var status: Int?
    public var count: Int?
    public var lastLoginDate: Date?
    public var registerDatetime: Date?

    public init(_id: Int? = nil, groupId: Int? = nil, name: String? = nil, surname: String? = nil, username: String? = nil, email: String? = nil, gsm: String? = nil, password: String? = nil, status: Int? = nil, count: Int? = nil, lastLoginDate: Date? = nil, registerDatetime: Date? = nil) {
        self._id = _id
        self.groupId = groupId
        self.name = name
        self.surname = surname
        self.username = username
        self.email = email
        self.gsm = gsm
        self.password = password
        self.status = status
        self.count = count
        self.lastLoginDate = lastLoginDate
        self.registerDatetime = registerDatetime
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case groupId
        case name
        case surname
        case username
        case email
        case gsm
        case password
        case status
        case count
        case lastLoginDate
        case registerDatetime
    }

}
